package tamil.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2016-AUG-19  11:27:51 AM
 */
public class grMerchants2 extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for grMerchants2.
    */
    public grMerchants2() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("grMerchants2.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

