package sinhala.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2016-AUG-19  11:31:32 AM
 */
public class grPromotions extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for grPromotions.
    */
    public grPromotions() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("grPromotions.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

