package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Dialog Designer at: 2016-AUG-05  10:28:13 AM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Dialog Designer at: 2016-AUG-05  10:28:13 AM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("userData");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.MERCHANT_2VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.MERCHANT_3VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MERCHANT_2PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.MERCHANT_4VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.START, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.MERCHANT_1VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MERCHANTS_PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SERVICE_SELECT_PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PROMOTIONS_VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.LANGUAGE_SELECT_PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.END, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CHECK_MAX_TRIES_FIELD_INITIAL_VALUE,
			IProjectVariables.CHECK_MAX_TRIES_FIELD_NO_OF_TRIES };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CHECK_MAX_TRIES, variableFields, new String[] {"0", "0"}, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.PRODUCT_INFO_VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.MERCHANTS_VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.AGENT_TRANFER_VDN, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MERCHANT_1PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.AGENT_TRANSFER, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MERCHANT_4PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.SERVICE_VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_COLUMN_0,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_CONFIDENCE,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_INPUTMODE,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_INTERPRETATION,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_NOINPUTCOUNT,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_NOMATCHCOUNT,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_UTTERANCE,
			IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.MERCHANT_3PROMPT_AND_COLLECT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_COLUMN_0,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_CONFIDENCE,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_INPUTMODE,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_INTERPRETATION,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_NOINPUTCOUNT,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_NOMATCHCOUNT,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_UTTERANCE,
			IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PROMOTIONS_PROMPT_AND_COLLECT_COPY, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.CLID, "", null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.LANG_VALUE, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_COLUMN_0,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_CONFIDENCE,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_INPUTMODE,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_INTERPRETATION,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_NOINPUTCOUNT,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_NOMATCHCOUNT,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_UTTERANCE,
			IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PRODUCT_INFORMATION_PROMPT_AND_COLLECT_COPY, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public String getEntryName() {
		return("GenieServices");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Dialog Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Dialog Designer at: 2016-SEP-27  09:04:58 AM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
