package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Dialog Designer at: 2016-AUG-19  11:30:09 AM
 */
public class grMerchants4 extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for grMerchants4.
    */
    public grMerchants4() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("grMerchants4.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

